### ISSUE TITLE
TypeError: QtSidebar.update() missing 1 required positional argument: 'w'

### ISSUE THREAD

**Issue by mschutter05** [sam210723/wavebin#15]
In line 182 of interface.py there is the following call to update with only 3 arguments:
`self.sidebar.update(0, False, -1)`

This was resulting in the following every time I tried to open a .bin file:
`TypeError: QtSidebar.update() missing 1 required positional argument: 'w'`

After changing line 182 to the following by adding None argument I was able to open the file without getting TypeError:
`self.sidebar.update(0, False, -1, None)`

I don't know what I did or if it is a proper fix.

**Comment by sam210723** [comment]
Looks like I missed this because my testing uses the `-i` argument to open the waveform files rather than File -> Open. You were pretty much correct with your fix, but I've used `0` for that argument so the channel selector drop down in the sidebar is cleared correctly.

I've released v2.3.1 with this fix.
