### ISSUE TITLE
wave_colours limits number of waveforms to 2

### ISSUE THREAD

**Issue by natepallo** [sam210723/wavebin#5]
Ran into an issue with an MSO-X 4154A binary file. It's 4 traces, but in __main__, wave_colours only has two colors available so an exception is thrown in render() at "...pen=pg.mkPen(wave_colours[i]..."

Adding two more colors to the list allowed it to plot. Unfortunately, I cannot upload the .bin here, but I can share it in Drive.

https://drive.google.com/file/d/1lbOBTAwaHBapVnIGiAOSuQmzsr33FTF1/view?usp=sharing

-Nate

**Comment by sam210723** [comment]
Hey Nate,

Thanks for the MSO-X sample. I've added it to the repo and removed your S/N from the file.

Colours for channels 3 and 4 have been added. I've also added an adjustable subsampling limit (`-s` option) since I wasn't able to render all 8,000,000 points in this capture. Do you happen to have a screenshot of the waveform on the scope for comparison? Channels 1 and 2 don't seem to be rendering correctly (see screenshot).

![](https://user-images.githubusercontent.com/5117093/104554385-d8096480-5687-11eb-9eb8-8aac337bddee.png)


Regards,
Sam.

**Comment by sam210723** [comment]
Completely re-written v2.0 is now live. Tested ok with MSO-X 4154A sample.
